- name: Nginx
  hosts: webservers
  become: true
  vars:
    ansible_ssh_user: user

  tasks:
    - name: Install_nginx
      package:
        name: nginx
        update_cache: true

    - name: Starting_nginx
      service:
        name: nginx
        state: started
        enabled: true
